# Generated by Django 4.1.7 on 2024-03-23 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_this_job_is_available',
            field=models.BooleanField(default=True),
        ),
    ]
