# Generated by Django 4.1.7 on 2024-03-23 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_job_is_this_job_is_available'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='is_this_job_is_available',
            new_name='is_available',
        ),
    ]
