# Generated by Django 4.1.7 on 2024-03-23 08:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_rename_is_this_job_is_available_job_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='timestamb',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
