# Generated by Django 4.1.7 on 2024-03-23 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_remove_job_ideal_candidate_remove_job_requirements_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyjob',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes'),
        ),
    ]
