# Generated by Django 4.1.7 on 2024-03-23 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_job_cover_letter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='cover_letter',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
