# Generated by Django 5.0.3 on 2024-03-26 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0013_alter_applyjob_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='salary_Range',
        ),
    ]
